baseURL: "https://alenabraham.me/"
#baseURL: "https://abrahamalen.github.io/alen-abraham.github.io/"
title: Alen Abraham
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 200000
pygmentsStyle: bw
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
enableEmoji: true

disqusShortname: alenabraham

params:
  title: "Alen Abraham"
  description: "Software Engineer passionate about Cloud, DevOps and Security."
  keywords: [Alen, Abraham, Blog, Portfolio, Resume]
  info:
    - Software Engineer
    - DevOps | SRE | Cloud
 # author: "Alen Abraham"
  avatarURL: images/avatar.png
  dateFormat: "January 2, 2006"
  since: 2022
  commit: "https://github.com/luizdepra/hugo-coder/tree/"
  rtl: false
  colorScheme: auto #dark, light
  hideColorSchemeToggle: false
  maxSeeAlsoItems: 5
  customCSS: []
  customSCSS: []
  customJS: []

  minify:
    disableXML: true
    minifyOutput: true

  mainSections: ["posts"]

  ShowReadingTime: true
  ShowLastMod: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  # showtoc: false
  # tocopen: false

  images:
    [
      "/images/preview.png", "Alen Abraham", "https://alenabraham.me",
    ]

  subscribeInfo:
    Text: If you liked this post, check out my other [Featured Posts](/categories/featured) or learn more [About Me](/about).
  csp:
    childsrc:
      - "'self'"
    fontsrc:
      - "'self'"
      - "https://fonts.gstatic.com"
      - "https://cdn.jsdelivr.net/"
    formaction:
      - "'self'"
    framesrc:
      - "'self'"
    imgsrc:
      - "'self'"
    objectsrc:
      - "'none'"
    stylesrc:
      - "'self'"
      - "'unsafe-inline'"
      - "https://fonts.googleapis.com/"
      - "https://cdn.jsdelivr.net/"
    scriptsrc:
      - "'self'"
      - "'unsafe-inline'"
      - "https://www.google-analytics.com"
      - "https://cdn.jsdelivr.net/"
    prefetchsrc:
      - "'self'"
    connectsrc:
      - "'self'"
      - "https://www.google-analytics.com"

  social:
    - name: Github
      icon: fa fa-2x fa-github
      weight: 1
      url: "https://github.com/abrahamalen/"
    - name: Twitter
      icon: fa fa-2x fa-twitter
      weight: 2
      url: "https://twitter.com/op__trojan/"
    - name: LinkedIn
      icon: fa fa-2x fa-linkedin
      weight: 3
      url: "https://www.linkedin.com/in/alenabraham/"
    - name: "Behance"
      icon: "fa fa-behance fa-2x"
      weight: 4
      url: "https://www.behance.net/alenabraham"
    - name: Medium
      icon: fa fa-2x fa-medium
      weight: 5
      url: "https://medium.com/@alen-abraham"
    - name: Buy me a coffee
      icon: "fa fa-buymeacoffee fa-2x"
      weight: 6
      url: "https://www.buymeacoffee.com/alenabraham"
    # - name: RSS
    #   icon: fa fa-2x fa-rss
    #   weight: 6
    #   url: "https://myhugosite.com/index.xml"
    #   rel: alternate
    #   type: application/rss+xml

taxonomies:
  category: categories
  series: series
  tag: tags

languages:
  en:
    languageName: ":uk:"
    menu:
      main:
        # - name: Archives
        #   weight: 1
        #   url: archives/
        - name: About
          weight: 2
          url: about/
        - name: Posts
          weight: 3
          url: posts/
        - name: Categories
          weight: 4
          url: categories/
        #- name: Contact me
        #  weight: 3
        #  url: contact/
        # - name: Subscribe
        #   weight: 5
        #   url: subscribe/

cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page